import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { fetchBuyerManufacturerProducts, fetchBuyerManufacturers, manufacturerLocation, selectBuyerManufacturers, type BuyerManufacturer, type BuyerManufacturerSort } from "../../lib/buyerManufacturers";
import { marketplaceProductSlug } from "../../lib/marketplace";
import type { MarketplaceProduct } from "../../types";

interface Props { selectedManufacturerId: string | null; onSelectedManufacturerChange: (id: string | null) => void; }

export function BuyerManufacturersWorkspace({ selectedManufacturerId, onSelectedManufacturerChange }: Props) {
  const [items, setItems] = useState<BuyerManufacturer[]>([]);
  const [products, setProducts] = useState<MarketplaceProduct[]>([]);
  const [search, setSearch] = useState(""); const [country, setCountry] = useState(""); const [sort, setSort] = useState<BuyerManufacturerSort>("name");
  const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [failed, setFailed] = useState(false);
  const listSequence = useRef(0); const detailSequence = useRef(0);
  const load = useCallback(async () => { const seq = ++listSequence.current; setLoading(true); setFailed(false); try { const next = await fetchBuyerManufacturers(); if (seq === listSequence.current) setItems(next); } catch { if (seq === listSequence.current) setFailed(true); } finally { if (seq === listSequence.current) setLoading(false); } }, []);
  useEffect(() => { void load(); return () => { listSequence.current += 1; detailSequence.current += 1; }; }, [load]);
  const selected = items.find((item) => item.id === selectedManufacturerId) ?? null;
  useEffect(() => { const seq = ++detailSequence.current; setProducts([]); if (!selected) { setDetailLoading(false); return; } setDetailLoading(true); fetchBuyerManufacturerProducts(selected.id).then((next) => { if (seq === detailSequence.current) setProducts(next); }).catch(() => { if (seq === detailSequence.current) setFailed(true); }).finally(() => { if (seq === detailSequence.current) setDetailLoading(false); }); }, [selected?.id]);
  const countries = useMemo(() => [...new Set(items.map((item) => item.country).filter((value): value is string => Boolean(value)))].sort(), [items]);
  const visible = useMemo(() => selectBuyerManufacturers(items, search, country, sort), [items, search, country, sort]);
  const clear = () => { setSearch(""); setCountry(""); };
  if (loading) return <section aria-labelledby="buyer-manufacturers-heading" aria-busy="true"><h3 id="buyer-manufacturers-heading">Manufacturers</h3><div role="status">Loading manufacturers...</div></section>;
  if (failed) return <section aria-labelledby="buyer-manufacturers-heading"><h3 id="buyer-manufacturers-heading">Manufacturers</h3><div className="workspace-error" role="alert"><p>Unable to load manufacturers.</p><button type="button" onClick={() => void load()}>Retry</button></div></section>;
  if (selectedManufacturerId && !selected) return <section aria-labelledby="buyer-manufacturers-heading"><h3 id="buyer-manufacturers-heading">Manufacturer unavailable</h3><p>This manufacturer is not available in the approved directory.</p><button type="button" onClick={() => onSelectedManufacturerChange(null)}>Back to Manufacturers</button></section>;
  if (selected) return <ManufacturerDetail manufacturer={selected} products={products} loading={detailLoading} onBack={() => onSelectedManufacturerChange(null)} />;
  return <section className="marketplace-results manufacturer-directory" aria-labelledby="buyer-manufacturers-heading">
    <div className="workspace-toolbar"><div><p className="eyebrow">Buyer workspace</p><h3 id="buyer-manufacturers-heading">Manufacturers</h3><p>Discover approved manufacturers and their published Marketplace products.</p></div><a className="button-link" href="/marketplace">Marketplace</a></div>
    {items.length === 0 ? <div className="marketplace-state panel"><h4>No approved manufacturers available</h4><p>No approved Manufacturers are currently available.</p></div> : <>
      <div className="queue-controls" aria-label="Manufacturer directory controls"><label>Search manufacturers<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Name or location" /></label><label>Country<select value={country} onChange={(e) => setCountry(e.target.value)}><option value="">All countries</option>{countries.map((value) => <option key={value}>{value}</option>)}</select></label><label>Sort manufacturers<select value={sort} onChange={(e) => setSort(e.target.value as BuyerManufacturerSort)}><option value="name">Name A–Z</option><option value="products">Most products</option></select></label></div>
      {visible.length === 0 ? <div className="marketplace-state panel" role="status"><h4>No manufacturers match</h4><p>Try a different search or country.</p><button type="button" onClick={clear}>Clear Filters</button></div> : <div className="product-grid" role="list" aria-live="polite">{visible.map((item) => <article className="panel" role="listitem" key={item.id}><h4>{item.displayName}</h4><p>{manufacturerLocation(item)}</p>{item.description && <p>{item.description}</p>}<p><strong>{item.publishedProductCount}</strong> published {item.publishedProductCount === 1 ? "product" : "products"}</p>{item.certifications.length > 0 && <div className="tag-row" role="list" aria-label="Public certifications">{item.certifications.map((value) => <span role="listitem" key={value}>{value}</span>)}</div>}<div className="actions"><button type="button" onClick={() => onSelectedManufacturerChange(item.id)} aria-label={`View ${item.displayName} manufacturer details`}>View Manufacturer</button>{item.website && <a href={item.website} target="_blank" rel="noreferrer" aria-label={`Visit ${item.displayName} website`}>Website</a>}</div></article>)}</div>}
    </>}
  </section>;
}

function ManufacturerDetail({ manufacturer, products, loading, onBack }: { manufacturer: BuyerManufacturer; products: MarketplaceProduct[]; loading: boolean; onBack: () => void }) {
  return <section className="marketplace-results" aria-labelledby="manufacturer-detail-heading" aria-busy={loading}><button type="button" className="secondary" onClick={onBack}>Back to Manufacturers</button><div className="workspace-toolbar"><div><p className="eyebrow">Approved Manufacturer</p><h3 id="manufacturer-detail-heading">{manufacturer.displayName}</h3><p>{manufacturerLocation(manufacturer)}</p></div>{manufacturer.website && <a className="button-link" href={manufacturer.website} target="_blank" rel="noreferrer">Visit website</a>}</div>{manufacturer.description && <p>{manufacturer.description}</p>}{manufacturer.certifications.length > 0 && <><h4>Public certifications</h4><div className="tag-row" role="list">{manufacturer.certifications.map((value) => <span role="listitem" key={value}>{value}</span>)}</div></>}
    <h4>Published products</h4>{loading ? <p role="status">Loading published products...</p> : products.length === 0 ? <p>No published products are currently available.</p> : <div className="workspace-card-grid" role="list">{products.map((product) => <article className="panel" role="listitem" key={product.id}><h5>{product.model_name || product.name}</h5><p>{product.category}</p>{product.short_description && <p>{product.short_description}</p>}<a href={`/products/${encodeURIComponent(marketplaceProductSlug(product))}`} aria-label={`View ${product.model_name || product.name} in Marketplace`}>View Marketplace product</a></article>)}</div>}</section>;
}
