import test from "node:test";
import assert from "node:assert/strict";
import { buyerRFQHref, buyerRFQStatusFilter, filterBuyerRFQs, selectBuyerRFQs, shortRFQReference, sortBuyerRFQs } from "./buyerRfqList";
import { rfqStatuses } from "./rfq";
import type { RFQStatus, RFQWithDetails } from "../types";

const id = (digit: string) => `${digit.repeat(8)}-${digit.repeat(4)}-4${digit.repeat(3)}-8${digit.repeat(3)}-${digit.repeat(12)}`;
const record = (status: RFQStatus, digit: string, overrides: Partial<RFQWithDetails> = {}): RFQWithDetails => ({ id: id(digit), buyer_id: id("a"), manufacturer_id: id("b"), product_id: id("c"), product_snapshot: { name: `${status} Home`, model_name: `Model ${digit}`, manufacturer_display_name: `Maker ${digit}` }, status, requested_quantity: 1, requested_currency: "USD", incoterm: null, destination_country: "US", destination_port: null, target_delivery_date: null, buyer_message: null, created_at: `2026-01-0${digit}T00:00:00Z`, updated_at: `2026-02-0${digit}T00:00:00Z`, ...overrides });
const records = rfqStatuses.map((status, index) => record(status, String((index % 9) + 1)));

test("All retains every authorized RFQ and every known status has a group", () => { assert.equal(filterBuyerRFQs(records, "all", "").length, records.length); assert.deepEqual(Object.keys(buyerRFQStatusFilter).sort(), [...rfqStatuses].sort()); });
test("status groups map draft active review and closed lifecycle states", () => { assert.deepEqual(filterBuyerRFQs(records, "draft", "").map((r) => r.status), ["draft"]); assert.deepEqual(filterBuyerRFQs(records, "active", "").map((r) => r.status), ["submitted", "manufacturer_review", "revision_requested"]); assert.deepEqual(filterBuyerRFQs(records, "buyer_review", "").map((r) => r.status), ["quoted", "buyer_review"]); assert.deepEqual(filterBuyerRFQs(records, "closed", "").map((r) => r.status), ["accepted", "declined", "expired", "cancelled"]); });
test("search is trimmed case-insensitive and covers reference product model and manufacturer", () => { const target = records[0]; assert.deepEqual(filterBuyerRFQs(records, "all", `  ${shortRFQReference(target.id).toLowerCase()} `), records.filter((r) => r.id === target.id)); assert.deepEqual(filterBuyerRFQs(records, "all", "DRAFT HOME"), [target]); assert.deepEqual(filterBuyerRFQs(records, "all", "model 1"), records.filter((r) => r.product_snapshot.model_name === "Model 1")); assert.deepEqual(filterBuyerRFQs(records, "all", "maker 1"), records.filter((r) => r.product_snapshot.manufacturer_display_name === "Maker 1")); assert.equal(filterBuyerRFQs(records, "all", "no match").length, 0); });
test("sort modes are deterministic, tolerate malformed dates, and do not mutate input", () => { const source = [record("draft", "1"), record("accepted", "3"), record("quoted", "2", { updated_at: "invalid" })]; const original = [...source]; assert.deepEqual(sortBuyerRFQs(source, "updated").map((r) => r.status), ["accepted", "draft", "quoted"]); assert.deepEqual(sortBuyerRFQs(source, "created").map((r) => r.status), ["accepted", "quoted", "draft"]); assert.deepEqual(sortBuyerRFQs(source, "status").map((r) => r.status), ["draft", "quoted", "accepted"]); assert.deepEqual(source, original); assert.equal(selectBuyerRFQs(source, "closed", "", "updated").length, 1); });
test("canonical RFQ link uses record and never id", () => { const href = buyerRFQHref(id("1")); assert.equal(href, `/marketplace?view=dashboard&workspace=rfqs&record=${id("1")}`); assert.equal(href.includes("&id="), false); });
