import assert from "node:assert/strict";
import test from "node:test";
import type { ProfileRecord } from "../types";
import { fetchBuyerProfile, updateBuyerFullName, validateBuyerFullName, type BuyerProfileOperations } from "./buyerProfile";

const USER_ID = "11111111-1111-4111-8111-111111111111";
const profile = (overrides: Partial<ProfileRecord> = {}): ProfileRecord => ({ id: USER_ID, role: "buyer", full_name: "Buyer Name", email: "buyer@example.test", status: "active", created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z", ...overrides });
function operations(overrides: Partial<BuyerProfileOperations> = {}) { let selected = ""; let fetches = 0; const updates: string[] = []; const value: BuyerProfileOperations = { async getAuthIdentity() { return { id: USER_ID, email: "Buyer@Example.Test" }; }, async fetchProfile(id) { selected = id; fetches += 1; return profile({ full_name: updates.at(-1) ?? "Buyer Name" }); }, async updateFullName(value) { updates.push(value); }, ...overrides }; return { value, selected: () => selected, fetches: () => fetches, updates }; }

test("profile load derives identity from Auth and reads only that UUID", async () => { const mock = operations(); await fetchBuyerProfile(USER_ID, mock.value); assert.equal(mock.selected(), USER_ID); });
test("caller cannot substitute another profile UUID", async () => { const mock = operations(); await assert.rejects(fetchBuyerProfile("22222222-2222-4222-8222-222222222222", mock.value), /account changed/i); assert.equal(mock.fetches(), 0); });
test("profile UUID must match Auth", async () => { const mock = operations({ async fetchProfile() { return profile({ id: "22222222-2222-4222-8222-222222222222" }); } }); await assert.rejects(fetchBuyerProfile(USER_ID, mock.value), /unavailable/i); });
test("only active Buyers can load", async () => { for (const change of [{ role: "manufacturer" as const }, { status: "suspended" }]) { const mock = operations({ async fetchProfile() { return profile(change); } }); await assert.rejects(fetchBuyerProfile(USER_ID, mock.value), /unavailable/i); } });
test("missing profile fails closed", async () => { const mock = operations({ async fetchProfile() { return null; } }); await assert.rejects(fetchBuyerProfile(USER_ID, mock.value), /unavailable/i); });
test("Auth email is authoritative and normalized profile email must match", async () => { const mock = operations(); const result = await fetchBuyerProfile(USER_ID, mock.value); assert.equal(result.accountEmail, "Buyer@Example.Test"); const mismatch = operations({ async fetchProfile() { return profile({ email: "other@example.test" }); } }); await assert.rejects(fetchBuyerProfile(USER_ID, mismatch.value), /needs support/i); });
test("service errors are sanitized", async () => { const mock = operations({ async fetchProfile() { throw new Error("sql policy jwt secret"); } }); await assert.rejects(fetchBuyerProfile(USER_ID, mock.value), (error: Error) => error.message === "Profile service is unavailable."); });
test("full-name validation trims and rejects empty input", () => { assert.equal(validateBuyerFullName(" \n "), "Full name is required."); assert.equal(validateBuyerFullName(" Buyer "), null); });
test("full-name validation accepts 160 Unicode code points", () => { assert.equal(validateBuyerFullName("李".repeat(160)), null); });
test("full-name validation rejects more than 160 Unicode code points", () => { assert.match(validateBuyerFullName("李".repeat(161)) ?? "", /160/); });
test("update trims and sends only the approved full-name value", async () => { const mock = operations(); const result = await updateBuyerFullName(USER_ID, "  李 雷  ", mock.value); assert.deepEqual(mock.updates, ["李 雷"]); assert.equal(result.profile.full_name, "李 雷"); });
test("update verifies Auth identity before mutation", async () => { const mock = operations(); await assert.rejects(updateBuyerFullName("22222222-2222-4222-8222-222222222222", "Name", mock.value), /could not be updated/i); assert.deepEqual(mock.updates, []); });
test("update refetches authoritative profile after RPC success", async () => { const mock = operations(); await updateBuyerFullName(USER_ID, "New Name", mock.value); assert.equal(mock.fetches(), 1); assert.equal(mock.selected(), USER_ID); });
test("update rejects invalid input without Auth or RPC access", async () => { let authCalls = 0; const mock = operations({ async getAuthIdentity() { authCalls += 1; return { id: USER_ID, email: "buyer@example.test" }; } }); await assert.rejects(updateBuyerFullName(USER_ID, "   ", mock.value), /could not be updated/i); assert.equal(authCalls, 0); assert.deepEqual(mock.updates, []); });
test("RPC errors are sanitized", async () => { const mock = operations({ async updateFullName() { throw new Error("sql jwt policy project-url"); } }); await assert.rejects(updateBuyerFullName(USER_ID, "Buyer", mock.value), (error: Error) => error.message === "Profile could not be updated. Please try again."); });
test("post-update identity or role failures are sanitized", async () => { const mismatch = operations({ async fetchProfile() { return profile({ role: "admin" }); } }); await assert.rejects(updateBuyerFullName(USER_ID, "Buyer", mismatch.value), (error: Error) => error.message === "Profile could not be updated. Please try again."); });
test("operations expose no caller-selected field payload", () => { const mock = operations(); assert.deepEqual(Object.keys(mock.value).sort(), ["fetchProfile", "getAuthIdentity", "updateFullName"]); assert.equal(mock.value.updateFullName.length, 1); });
test("update forwards cancellation for logout and identity-switch containment", async () => { const controller = new AbortController(); let received: AbortSignal | undefined; const mock = operations({ async updateFullName(_name, signal) { received = signal; } }); await updateBuyerFullName(USER_ID, "Buyer", mock.value, controller.signal); assert.equal(received, controller.signal); });
