import test from "node:test";
import assert from "node:assert/strict";
import { run } from "./cli.mjs";
import { CONFIRM_CREATE, CONFIRM_RECOVERY, STAGING_PROJECT_REF } from "./core.mjs";
const EMAIL = "buyer.uat@example.test"; const UUID = "11111111-1111-4111-8111-111111111111";
function adapter() { const state = { recoveries: 0, creates: 0, role: "buyer" }; return { state, async findAuthUsersByEmail() { return [{ id: UUID, email: EMAIL, email_confirmed_at: "2026-01-01", banned_until: null, disabled: false }]; }, async findProfilesByEmail() { return [{ id: UUID, email: EMAIL, role: state.role, status: "active" }]; }, async requestPasswordRecovery() { state.recoveries += 1; }, async createAuthUser() { state.creates += 1; } }; }
const env = { PREFAB_BUYER_TARGET_PROJECT_REF: STAGING_PROJECT_REF, PREFAB_BUYER_SUPABASE_URL: `https://${STAGING_PROJECT_REF}.supabase.co`, PREFAB_BUYER_SERVICE_ROLE_KEY: "injected-test-value" };
test("dry-run emits plan and performs zero mutation", async () => { const mock = adapter(); let artifact; const result = await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], env, { adapter: mock, log() {}, writePlan: (value) => { artifact = value; return "plan.json"; } }); assert.equal(result.planPath, "plan.json"); assert.equal(artifact.payload.operation, "recovery"); assert.equal(mock.state.recoveries, 0); });
test("direct mutation without plan is rejected", async () => { await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--mode", "recovery"], env, { adapter: adapter(), log() {}, writeAudit: () => "audit.json" }), (e) => e.code === "PLAN_REQUIRED"); });
test("incomplete Auth inventory cannot produce a mutation plan", async () => { const mock = adapter(); mock.findAuthUsersByEmail = async () => { const error = new Error("partial inventory"); error.code = "INVENTORY_INCOMPLETE"; throw error; }; let writes = 0; await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], env, { adapter: mock, log() {}, writePlan: () => { writes += 1; } }), (e) => e.code === "INVENTORY_INCOMPLETE"); assert.equal(writes, 0); assert.equal(mock.state.creates, 0); });
test("recovery aborts if role changes during confirmation", async () => { const mock = adapter(); let artifact; await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], env, { adapter: mock, log() {}, writePlan: (value) => { artifact = value; return "plan.json"; } }); await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--mode", "recovery", "--plan", "plan.json"], env, { adapter: mock, log() {}, readPlan: () => artifact, confirm: async () => { mock.state.role = "admin"; return CONFIRM_RECOVERY; }, writeAudit: () => "audit.json" }), (e) => e.code === "PLAN_INVENTORY_CHANGED"); assert.equal(mock.state.recoveries, 0); });
test("approved recovery sends once", async () => { const mock = adapter(); let artifact; await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], env, { adapter: mock, log() {}, writePlan: (value) => { artifact = value; return "plan.json"; } }); const result = await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--mode", "recovery", "--plan", "plan.json"], env, { adapter: mock, log() {}, readPlan: () => artifact, confirm: async () => CONFIRM_RECOVERY, gitCommit: () => "abc", writeAudit: () => "audit.json" }); assert.equal(result.outcome, "recovery_requested"); assert.equal(mock.state.recoveries, 1); });
test("contained plan failure writes redacted audit", async () => { const records = []; const sensitiveReason = ["sb", "secret", "abcdefghijklmnop"].join("_"); await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", sensitiveReason, "--mode", "recovery"], env, { adapter: adapter(), log() {}, writeAudit: (record) => { records.push(record); return "audit.json"; } }), (e) => e.code === "PLAN_REQUIRED"); assert.equal(records.length, 1); assert.equal(JSON.stringify(records).includes(sensitiveReason), false); assert.equal(records[0].outcome, "contained_failure"); });
test("recovery success plus audit failure has an explicit non-retry outcome", async () => { const mock = adapter(); let artifact; const diagnostics = []; await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], env, { adapter: mock, log() {}, writePlan: (value) => { artifact = value; return "plan.json"; } }); await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--mode", "recovery", "--plan", "plan.json"], env, { adapter: mock, log() {}, errorLog: (value) => diagnostics.push(value), readPlan: () => artifact, confirm: async () => CONFIRM_RECOVERY, gitCommit: () => "abc", writeAudit: () => { throw new Error("disk full"); } }), (e) => e.code === "MUTATION_SUCCEEDED_AUDIT_FAILED" && e.remoteMutationSucceeded); assert.equal(mock.state.recoveries, 1); assert.match(diagnostics[0], /Do not retry blindly/); assert.equal(diagnostics[0].includes(env.PREFAB_BUYER_SERVICE_ROLE_KEY), false); });
test("create success plus audit failure cannot cause a second create", async () => { const state = { auth: [], profiles: [], creates: 0 }; const mock = { state, async findAuthUsersByEmail() { return state.auth; }, async findProfilesByEmail() { return state.profiles; }, async createAuthUser() { state.creates += 1; const row = { id: UUID, email: EMAIL, email_confirmed_at: "2026-01-01", banned_until: null, disabled: false }; state.auth = [row]; state.profiles = [{ id: UUID, email: EMAIL, role: "buyer", status: "active" }]; return row; }, async waitForProfile() {} }; const createEnv = { ...env, PREFAB_BUYER_TEMP_PASSWORD: "temporary-test-only" }; let artifact; await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], createEnv, { adapter: mock, log() {}, writePlan: (value) => { artifact = value; return "plan.json"; } }); await assert.rejects(run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--mode", "create", "--plan", "plan.json"], createEnv, { adapter: mock, log() {}, errorLog() {}, readPlan: () => artifact, confirm: async () => CONFIRM_CREATE, gitCommit: () => "abc", writeAudit: () => { throw new Error("disk full"); } }), (e) => e.code === "MUTATION_SUCCEEDED_AUDIT_FAILED"); assert.equal(state.creates, 1); const next = await run(["--environment", "staging", "--email", EMAIL, "--reason", "UAT", "--dry-run"], createEnv, { adapter: mock, log() {}, writePlan: () => "next.json" }); assert.equal(next.artifact.payload.operation, "recovery"); assert.equal(state.creates, 1); });
